# 测试用例Sheet识别（只要包含此列即为测试用例Sheet）
testcase.required.column=模块编号

# 基本信息Sheet识别（第一列，第二列，第三列）
basicinfo.column.tablename=表格名称
basicinfo.column.fieldname=字段名
basicinfo.column.fieldvalue=字段值

# 列表型Sheet识别（第一列名称）
listdata.column.tablename=表格名称

# 是否启用调试日志
debug.enabled=false